### ISSUE TITLE
Memory leak when constantly loading/unloading worlds

### ISSUE THREAD

**Issue by MagMaad** [mcpvp-club/FasterCrystals#26]
For practice servers that find themself loading & unloading tons of worlds, it appears crystals do not get removed from memory. I understand my way of going about arena creation is quite unusual, but it's always good to make sure unnecessary object references aren't retained.

Confirmed this by analyzing a heapdump. The issue is also **not** present on my instances with a regular world setup

![9ce1582e-774c-4b74-b851-0b8774e54367](https://github.com/user-attachments/assets/6f26d4fe-1194-4c65-8bf6-105dbda1eff3)

**Comment by Jyguy** [comment]
Thanks for the report!
